### ISSUE TITLE
ArtifactBuilder stack depends_on issue

### ISSUE THREAD

**Issue by mattsb42-aws** [mattsb42/accretion#34]
I ran into an intermittent issue with a deployment in a single region failing with a `InsufficientS3BucketPolicyException` error. It looks like this is due to the CloudTrail trail starting creation before the bucket policy is finished[1].
This can be easily fixed by adding a `DependsOn` manual relationship link between the two.

[1] https://github.com/hashicorp/terraform/issues/6388

**Comment by mattsb42** [comment]
closing project as discussed in #35
